const FETCH_COCKTAIL_START="FETCH_COCKTAIL_START" ;
const FETCH_COCKTAIL_SUCCESS="FETCH_COCKTAIL_SUCCESS" ;
const FETCH_COCKTAIL_FAILURE="FETCH_COCKTAIL_FAILURE" ;

const SEARCH_COCKTAIL_START="SEARCH_COCKTAIL_START" ;
const SEARCH_COCKTAIL_SUCCESS="SEARCH_COCKTAIL_SUCCESS" ;
const SEARCH_COCKTAIL_FAILURE="SEARCH_COCKTAIL_FAILURE" ;

const GET_SINGLE_COCKTAIL_START="GET_SINGLE_COCKTAIL_START" ;
const GET_SINGLE_COCKTAIL_SUCCESS="GET_SINGLE_COCKTAIL_SUCCESS" ;
const GET_SINGLE_COCKTAIL_FAILURE="GET_SINGLE_COCKTAIL_FAILURE" ;

export {FETCH_COCKTAIL_FAILURE,FETCH_COCKTAIL_SUCCESS,FETCH_COCKTAIL_START ,GET_SINGLE_COCKTAIL_FAILURE,GET_SINGLE_COCKTAIL_SUCCESS,GET_SINGLE_COCKTAIL_START,SEARCH_COCKTAIL_FAILURE,SEARCH_COCKTAIL_START,SEARCH_COCKTAIL_SUCCESS}