const FETCH_COCKTAIL_START="FETCH_COCKTAIL_START" ;
const FETCH_COCKTAIL_SUCCESS="FETCH_COCKTAIL_SUCCESS" ;
const FETCH_COCKTAIL_FAILURE="FETCH_COCKTAIL_FAILURE" ;

export {FETCH_COCKTAIL_FAILURE,FETCH_COCKTAIL_SUCCESS,FETCH_COCKTAIL_START}